general:
  s3_regional_buckets: true
project:
  name: quickstart-mongodb-atlas
  owner: quickstart-eng@amazon.com
  shorten_stack_name: true
tests:
  mdb-atlas:
    regions:
      - us-east-1
    parameters:
      OrgId: override
      ProjectName: tcat-$[taskcat_random-string]-$[taskcat_current_region]
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      ClusterName: tcat-$[taskcat_random-string]-$[taskcat_current_region]
      ClusterRegion: US_EAST_1
      DatabasePassword: $[taskcat_genpass_12]
    template: templates/mongodb-atlas-main.template.yaml
  mdb-atlas-vpc:
    regions:
      - us-west-1
    parameters:
      OrgId: override
      ProjectName: tcat-$[taskcat_random-string]-$[taskcat_current_region]
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      RouteTableCIDRBlock: 10.8.0.0/21
      AvailabilityZones: $[taskcat_genaz_2]
      ClusterName: tcat-$[taskcat_random-string]-$[taskcat_current_region]
      ClusterRegion: US_WEST_1
      DatabasePassword: $[taskcat_genpass_12]
    template: templates/mongodb-atlas-peering-newvpc.template.yaml
  mdb-atlas-pvt-endpoint:
    regions:
      - us-east-2
    parameters:
      OrgId: override
      ProjectName: tcat-$[taskcat_random-string]-$[taskcat_current_region]
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      ClusterRegion: US_EAST_2
      AvailabilityZone: us-east-2a
      VPCRegion: $[taskcat_current_region]
      ClusterName: tcat-$[taskcat_random-string]-$[taskcat_current_region]
      DatabasePassword: $[taskcat_genpass_12]
    template: templates/mongodb-atlas.private-endpoint.template.yaml